site_name: Soccer-Cast Docs
repo_url: https://github.com/WildCayote/Soccer-Cast
theme:
  name: material
  language: en
  icon:
    - repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.top
    - navigation.expand
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
