name: compare_metrics
on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: install requirements
        run: |
          pip install -r requirements.txt
      - name: run the experiment
        run: |
          dvc repro
      - name: generate report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # generate report
          git fetch --prune
          dvc metrics diff --show-md master > report.md

          cml-send-comment report.md
