name: compare_metrics
on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.14"
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install dvc[all]  # Ensure all DVC dependencies are installed
          pip install --upgrade cryptography  # Update cryptography library
          pip install -r requirements.txt
      - name: run the experiment
        run: |
          dvc pull
          dvc repro
      - name: generate report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # generate report
          git fetch --prune
          dvc metrics diff --show-md master > report.md

          cml-send-comment report.md
