name: compare_metrics
on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: install requirements
        run: |
          pip install -r requirements.txt
